version: '3.9'

services:
  web:
    image: "node-app-test-new:latest"
    deploy:
      replicas: 1
    ports:
      - "8000:8000"
  web2:
    image: "node-app-test-new:latest"
    deploy:
      replicas: 1
    ports:
      - "8001:8000"
