version: '3.9'

services:
  web:
    image: "node-app-test-new:latest"
    deploy:
      replicas: 2
    ports:
      - "8000:8000"
  nginx:
    image: "nginx:latest"
    depends_on:
      web
    ports:
      - "3000:3000"
